### ISSUE TITLE
Error when file already exists

### ISSUE THREAD

**Issue by av1m** [ryan-rozario/pipreqs-action#1]
Hello,
First of all thank you for this Github Actions.
I noticed that once the `requirement.txt` file is created, all new calls fail.
Docker indicates that no changes have been made, so Github Actions returns an error
You can see an example [here](https://github.com/av1m/learn-python/runs/620715584?check_suite_focus=true)

**Comment by afonsoVale** [comment]
Also experiencing the same

**Comment by av1m** [comment]
A solution in the meantime is to put `requirements.txt` in `.gitignore` (or to rename it if necessary)
