### ISSUE TITLE
missing line in requirements.txt

### ISSUE THREAD

**Issue by zkoppert** [ryan-rozario/pipreqs-action#6]
Really like this action but one of my projects is getting a bad requirements.txt file.

When I run this in my project https://github.com/zkoppert/innersource-crawler

The action yields
```bash
ratelimiter==1.2.0.post0
python-dotenv==0.15.0
```
but it should be
```bash
github3.py==1.3.0
ratelimiter==1.2.0.post0
python-dotenv==0.15.0
```

I looked at what is in the `entrypoint.sh` in this action repo, and it shows it runs `pipreqs --force`. When I run that locally on my project (not using a docker container) I get the expected results as shown below.
```
Zacherys-MacBook-Pro:innersource-crawler zkoppert$  pipreqs --force
INFO: Successfully saved requirements file in /Users/zkoppert/repos/innersource-crawler/requirements.txt
Zacherys-MacBook-Pro:innersource-crawler zkoppert$ cat requirements.txt 
github3.py==1.3.0
ratelimiter==1.2.0.post0
python-dotenv==0.15.0
Zacherys-MacBook-Pro:innersource-crawler zkoppert$
```

Any ideas as to why the action isn't the same as running pipreqs myself? Happy to help debug if there is anything you think I should check.

**Comment by ryan-rozario** [comment]
bndr/pipreqs#238 has been merged. This will fix this issue in the next release of pipreqs.
